// app/glossary/page.tsx
"use client";

type GlossaryItem = {
  term: string;
  definition: string;
  link: string;
};

const glossary: GlossaryItem[] = [
  {
    term: "Datacenter",
    definition:
      "A facility used to house computer systems and associated components, such as telecommunications and storage systems. Datacenters consume large amounts of energy, especially when powering AI models.",
    link: "https://en.wikipedia.org/wiki/Data_center",
  },
  {
    term: "kWh (kilowatt-hour)",
    definition:
      "A measure of energy equivalent to one kilowatt (1 kW) of power used for one hour. Often used to express the energy consumption of data centers and AI models.",
    link: "https://en.wikipedia.org/wiki/Kilowatt-hour",
  },
  {
    term: "Carbon Footprint",
    definition:
      "The total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. In AI, it's often tied to model training and inference.",
    link: "https://en.wikipedia.org/wiki/Carbon_footprint",
  },
  {
    term: "Inference",
    definition:
      "The process of using a trained AI model to make predictions. While less energy-intensive than training, frequent inference still contributes to energy use.",
    link: "https://en.wikipedia.org/wiki/Artificial_neural_network#Inference",
  },
  {
    term: "Model Training",
    definition:
      "The process of feeding data to an AI model so it can learn patterns. This step consumes a significant amount of electricity and water, especially for large models.",
    link: "https://en.wikipedia.org/wiki/Training_(machine_learning)",
  },
];

export default function GlossaryPage() {
  return (
    <div className="space-y-6">
      {glossary.map((item, idx) => (
        <div
          key={idx}
          className="border-b border-pink-800 pb-4 hover:bg-gray-800 transition duration-200 rounded-md px-4 py-2"
        >
          <a
            href={item.link}
            target="_blank"
            rel="noopener noreferrer"
            className="text-pink-300 text-xl font-semibold hover:underline"
          >
            {item.term}
          </a>
          <p className="mt-1 text-gray-300">{item.definition}</p>
        </div>
      ))}
    </div>
  );
}
